### ISSUE TITLE
metabolic modeling code

### ISSUE THREAD

**Issue by Shakra-A** [AuReMe/aureme_docker#10]
Hi. I am new to this work. I have cds fasta file and I want to make the metabolic model from it. I read the documentation but it was confusing as there were reference model was mention. I do not want to used any other reference model. Can you guide me how to make the model only from a protein fasta file?

**Comment by jeannegot** [comment]
Hello,
If you have a GBK file of your species, you can build a metabolic metabolic model with Pathway Tools. If you don't have annotation (just protein sequences), you need to have proteome of another species with its metabolic network to compare a "reference model" with the species you want  to reconstruct.
Yes, I can guide you. 
Jeanne

**Comment by Shakra-A** [comment]
Thank you Jeanne. I don't want to use any reference model as I am looking for unique reactions. I think this tool does not support this.

**Comment by jeannegot** [comment]
Hello,
Before finding unique reactions, you should reconstruct a model. Our tool doesn't not find the unique reactions of a species.
Jeanne
